CREATE TABLE `accounts` (
  `account_id` int(8) NOT NULL AUTO_INCREMENT,
  `account_type` enum('Commercial','Government','Residential') DEFAULT NULL,
  `account_status` enum('Active','Pending','Closed','Lost','Retention','Drop','Off Contract') NOT NULL,
  `legal_name` varchar(255) NOT NULL,
  `corporation_name` varchar(255) DEFAULT NULL,
  `lead_source` varchar(255) DEFAULT NULL,
  `company_website` varchar(255) DEFAULT NULL,
  `billing_address` varchar(255) NOT NULL,
  `billing_address2` varchar(255) NOT NULL,
  `billing_unit` varchar(255) NOT NULL,
  `billing_city` varchar(255) NOT NULL,
  `billing_state` varchar(255) NOT NULL,
  `billing_zipcode` varchar(5) NOT NULL,
  `tax_excempt` tinyint(4) NOT NULL,
  `contact_first_name` varchar(255) NOT NULL,
  `contact_last_name` varchar(255) NOT NULL,
  `contact_title` varchar(255) NOT NULL,
  `contact_dob` varchar(255) DEFAULT NULL,
  `contact_email` varchar(255) NOT NULL,
  `contact_phone` varchar(30) DEFAULT NULL,
  `contact_cell` varchar(30) DEFAULT NULL,
  `contact_fax` varchar(30) DEFAULT NULL,
  `contact2_first_name` varchar(255) DEFAULT NULL,
  `contact2_last_name` varchar(255) DEFAULT NULL,
  `contact2_title` varchar(255) DEFAULT NULL,
  `contact2_email` varchar(255) DEFAULT NULL,
  `contact2_phone` varchar(12) DEFAULT NULL,
  `tax_id` varchar(40) DEFAULT NULL,
  `duns` varchar(40) DEFAULT NULL,
  `sic_code` varchar(40) DEFAULT NULL,
  `upload_files` varchar(255) NOT NULL,
  `price_product` varchar(255) DEFAULT NULL,
  `price_product_type` varchar(255) DEFAULT NULL,
  `anual_usage` varchar(10) DEFAULT NULL,
  `price_state` varchar(255) NOT NULL,
  `price_utility` varchar(255) NOT NULL,
  `price_utility2` varchar(255) DEFAULT NULL,
  `price_area` varchar(5) NOT NULL,
  `load_profile` varchar(20) DEFAULT NULL,
  `admin_fee` varchar(10) DEFAULT NULL,
  `channel_partner_fee` varchar(10) DEFAULT NULL,
  `under_contract` enum('YES','NO','NOT SURE') NOT NULL,
  `last_contract_price` varchar(10) DEFAULT NULL,
  `last_term` varchar(10) DEFAULT NULL,
  `last_contract_end` varchar(10) DEFAULT NULL,
  `requested_margin` varchar(12) NOT NULL,
  `auction_start_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `auction_end_price` varchar(10) DEFAULT NULL,
  `contract_start` varchar(10) DEFAULT NULL,
  `account_auction_note` varchar(1024) DEFAULT NULL,
  `assoc_customer` int(20) DEFAULT NULL,
  `user_id` int(8) NOT NULL,
  `created_on` timestamp NULL DEFAULT NULL,
  `timestamp` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `user_name` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`account_id`),
  UNIQUE KEY `account_id` (`account_id`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=505266 DEFAULT CHARSET=utf8
